/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { UserBadge } from "./UserBadge";
import { UserBadgeCountArgs } from "./UserBadgeCountArgs";
import { UserBadgeFindManyArgs } from "./UserBadgeFindManyArgs";
import { UserBadgeFindUniqueArgs } from "./UserBadgeFindUniqueArgs";
import { CreateUserBadgeArgs } from "./CreateUserBadgeArgs";
import { UpdateUserBadgeArgs } from "./UpdateUserBadgeArgs";
import { DeleteUserBadgeArgs } from "./DeleteUserBadgeArgs";
import { User } from "../../user/base/User";
import { UserBadgeService } from "../userBadge.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => UserBadge)
export class UserBadgeResolverBase {
  constructor(
    protected readonly service: UserBadgeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "UserBadge",
    action: "read",
    possession: "any",
  })
  async _userBadgesMeta(
    @graphql.Args() args: UserBadgeCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [UserBadge])
  @nestAccessControl.UseRoles({
    resource: "UserBadge",
    action: "read",
    possession: "any",
  })
  async userBadges(
    @graphql.Args() args: UserBadgeFindManyArgs
  ): Promise<UserBadge[]> {
    return this.service.userBadges(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => UserBadge, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "UserBadge",
    action: "read",
    possession: "own",
  })
  async userBadge(
    @graphql.Args() args: UserBadgeFindUniqueArgs
  ): Promise<UserBadge | null> {
    const result = await this.service.userBadge(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => UserBadge)
  @nestAccessControl.UseRoles({
    resource: "UserBadge",
    action: "create",
    possession: "any",
  })
  async createUserBadge(
    @graphql.Args() args: CreateUserBadgeArgs
  ): Promise<UserBadge> {
    return await this.service.createUserBadge({
      ...args,
      data: {
        ...args.data,

        user: {
          connect: args.data.user,
        },
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => UserBadge)
  @nestAccessControl.UseRoles({
    resource: "UserBadge",
    action: "update",
    possession: "any",
  })
  async updateUserBadge(
    @graphql.Args() args: UpdateUserBadgeArgs
  ): Promise<UserBadge | null> {
    try {
      return await this.service.updateUserBadge({
        ...args,
        data: {
          ...args.data,

          user: {
            connect: args.data.user,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => UserBadge)
  @nestAccessControl.UseRoles({
    resource: "UserBadge",
    action: "delete",
    possession: "any",
  })
  async deleteUserBadge(
    @graphql.Args() args: DeleteUserBadgeArgs
  ): Promise<UserBadge | null> {
    try {
      return await this.service.deleteUserBadge(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(@graphql.Parent() parent: UserBadge): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
