/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { MatchCreateNestedManyWithoutUsersInput } from "./MatchCreateNestedManyWithoutUsersInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { Match } from "../../match/base/Match";
import { PhotoCreateNestedManyWithoutUsersInput } from "./PhotoCreateNestedManyWithoutUsersInput";
import { Photo } from "../../photo/base/Photo";
import { ProfilWhereUniqueInput } from "../../profil/base/ProfilWhereUniqueInput";
import { Profil } from "../../profil/base/Profil";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: () => MatchCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => MatchCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => MatchCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  Match?: MatchCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => PhotoCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => PhotoCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => PhotoCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  Photo?: PhotoCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => ProfilWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ProfilWhereUniqueInput)
  @IsOptional()
  @Field(() => ProfilWhereUniqueInput, {
    nullable: true,
  })
  Profil?: ProfilWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;
}

export { UserCreateInput as UserCreateInput };
