/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { GroupMemberService } from "../groupMember.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { GroupMemberCreateInput } from "./GroupMemberCreateInput";
import { GroupMember } from "./GroupMember";
import { GroupMemberFindManyArgs } from "./GroupMemberFindManyArgs";
import { GroupMemberWhereUniqueInput } from "./GroupMemberWhereUniqueInput";
import { GroupMemberUpdateInput } from "./GroupMemberUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class GroupMemberControllerBase {
  constructor(
    protected readonly service: GroupMemberService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: GroupMember })
  @nestAccessControl.UseRoles({
    resource: "GroupMember",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createGroupMember(
    @common.Body() data: GroupMemberCreateInput
  ): Promise<GroupMember> {
    return await this.service.createGroupMember({
      data: {
        ...data,

        group: {
          connect: data.group,
        },

        user: {
          connect: data.user,
        },
      },
      select: {
        group: {
          select: {
            id: true,
          },
        },

        id: true,
        joinedAt: true,
        role: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [GroupMember] })
  @ApiNestedQuery(GroupMemberFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "GroupMember",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async groupMembers(@common.Req() request: Request): Promise<GroupMember[]> {
    const args = plainToClass(GroupMemberFindManyArgs, request.query);
    return this.service.groupMembers({
      ...args,
      select: {
        group: {
          select: {
            id: true,
          },
        },

        id: true,
        joinedAt: true,
        role: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: GroupMember })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "GroupMember",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async groupMember(
    @common.Param() params: GroupMemberWhereUniqueInput
  ): Promise<GroupMember | null> {
    const result = await this.service.groupMember({
      where: params,
      select: {
        group: {
          select: {
            id: true,
          },
        },

        id: true,
        joinedAt: true,
        role: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: GroupMember })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "GroupMember",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateGroupMember(
    @common.Param() params: GroupMemberWhereUniqueInput,
    @common.Body() data: GroupMemberUpdateInput
  ): Promise<GroupMember | null> {
    try {
      return await this.service.updateGroupMember({
        where: params,
        data: {
          ...data,

          group: {
            connect: data.group,
          },

          user: {
            connect: data.user,
          },
        },
        select: {
          group: {
            select: {
              id: true,
            },
          },

          id: true,
          joinedAt: true,
          role: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: GroupMember })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "GroupMember",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteGroupMember(
    @common.Param() params: GroupMemberWhereUniqueInput
  ): Promise<GroupMember | null> {
    try {
      return await this.service.deleteGroupMember({
        where: params,
        select: {
          group: {
            select: {
              id: true,
            },
          },

          id: true,
          joinedAt: true,
          role: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
