/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { SocialAccount } from "./SocialAccount";
import { SocialAccountCountArgs } from "./SocialAccountCountArgs";
import { SocialAccountFindManyArgs } from "./SocialAccountFindManyArgs";
import { SocialAccountFindUniqueArgs } from "./SocialAccountFindUniqueArgs";
import { CreateSocialAccountArgs } from "./CreateSocialAccountArgs";
import { UpdateSocialAccountArgs } from "./UpdateSocialAccountArgs";
import { DeleteSocialAccountArgs } from "./DeleteSocialAccountArgs";
import { User } from "../../user/base/User";
import { SocialAccountService } from "../socialAccount.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => SocialAccount)
export class SocialAccountResolverBase {
  constructor(
    protected readonly service: SocialAccountService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "SocialAccount",
    action: "read",
    possession: "any",
  })
  async _socialAccountsMeta(
    @graphql.Args() args: SocialAccountCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [SocialAccount])
  @nestAccessControl.UseRoles({
    resource: "SocialAccount",
    action: "read",
    possession: "any",
  })
  async socialAccounts(
    @graphql.Args() args: SocialAccountFindManyArgs
  ): Promise<SocialAccount[]> {
    return this.service.socialAccounts(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => SocialAccount, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "SocialAccount",
    action: "read",
    possession: "own",
  })
  async socialAccount(
    @graphql.Args() args: SocialAccountFindUniqueArgs
  ): Promise<SocialAccount | null> {
    const result = await this.service.socialAccount(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => SocialAccount)
  @nestAccessControl.UseRoles({
    resource: "SocialAccount",
    action: "create",
    possession: "any",
  })
  async createSocialAccount(
    @graphql.Args() args: CreateSocialAccountArgs
  ): Promise<SocialAccount> {
    return await this.service.createSocialAccount({
      ...args,
      data: {
        ...args.data,

        user: {
          connect: args.data.user,
        },
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => SocialAccount)
  @nestAccessControl.UseRoles({
    resource: "SocialAccount",
    action: "update",
    possession: "any",
  })
  async updateSocialAccount(
    @graphql.Args() args: UpdateSocialAccountArgs
  ): Promise<SocialAccount | null> {
    try {
      return await this.service.updateSocialAccount({
        ...args,
        data: {
          ...args.data,

          user: {
            connect: args.data.user,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => SocialAccount)
  @nestAccessControl.UseRoles({
    resource: "SocialAccount",
    action: "delete",
    possession: "any",
  })
  async deleteSocialAccount(
    @graphql.Args() args: DeleteSocialAccountArgs
  ): Promise<SocialAccount | null> {
    try {
      return await this.service.deleteSocialAccount(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(@graphql.Parent() parent: SocialAccount): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
