/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field, Float } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsNumber,
  Max,
  IsOptional,
  IsString,
  MaxLength,
  IsEnum,
  ValidateNested,
} from "class-validator";
import { Decimal } from "decimal.js";
import { EnumProfilInterets } from "./EnumProfilInterets";
import { EnumProfilSexe } from "./EnumProfilSexe";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { Type } from "class-transformer";

@InputType()
class ProfilUpdateInput {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(3)
  @IsOptional()
  @Field(() => Float, {
    nullable: true,
  })
  age?: Decimal | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumProfilInterets,
    isArray: true,
  })
  @IsEnum(EnumProfilInterets, {
    each: true,
  })
  @IsOptional()
  @Field(() => [EnumProfilInterets], {
    nullable: true,
  })
  interets?: Array<
    | "Sport"
    | "Musique"
    | "Danse"
    | "Bar"
    | "Tv"
    | "Cinema"
    | "Karaoke"
    | "Dormir"
    | "Plage"
    | "Nature"
    | "JeuxVideo"
  >;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  localisation?: string | null;

  @ApiProperty({
    required: false,
    enum: EnumProfilSexe,
    isArray: true,
  })
  @IsEnum(EnumProfilSexe, {
    each: true,
  })
  @IsOptional()
  @Field(() => [EnumProfilSexe], {
    nullable: true,
  })
  sexe?: Array<"Masculin" | "Feminin">;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  utilisateurs?: UserWhereUniqueInput | null;
}

export { ProfilUpdateInput as ProfilUpdateInput };
