/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsString,
  MaxLength,
  IsOptional,
  IsDate,
  IsNumber,
  Max,
  IsInt,
  ValidateNested,
  IsEnum,
} from "class-validator";

import { Type } from "class-transformer";
import { EventParticipantCreateNestedManyWithoutEventsInput } from "./EventParticipantCreateNestedManyWithoutEventsInput";
import { EnumEventType } from "./EnumEventType";

@InputType()
class EventCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  city?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  country?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  description!: string;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  endDate!: Date;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  latitude?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  longitude?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  maxParticipants?: number | null;

  @ApiProperty({
    required: false,
    type: () => EventParticipantCreateNestedManyWithoutEventsInput,
  })
  @ValidateNested()
  @Type(() => EventParticipantCreateNestedManyWithoutEventsInput)
  @IsOptional()
  @Field(() => EventParticipantCreateNestedManyWithoutEventsInput, {
    nullable: true,
  })
  participants?: EventParticipantCreateNestedManyWithoutEventsInput;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  startDate!: Date;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  title!: string;

  @ApiProperty({
    required: true,
    enum: EnumEventType,
  })
  @IsEnum(EnumEventType)
  @Field(() => EnumEventType)
  type!: "SPEEDDATING" | "SOCIAL" | "WORKSHOP" | "OTHER";
}

export { EventCreateInput as EventCreateInput };
