import { UserBadge } from "../userBadge/UserBadge";
import { EventParticipant } from "../eventParticipant/EventParticipant";
import { GroupMember } from "../groupMember/GroupMember";
import { Notification } from "../notification/Notification";
import { Profile } from "../profile/Profile";
import { Like } from "../like/Like";
import { Message } from "../message/Message";
import { Report } from "../report/Report";
import { SocialAccount } from "../socialAccount/SocialAccount";
import { Story } from "../story/Story";
import { Subscription } from "../subscription/Subscription";

export type User = {
  authMethod?: "EMAIL" | "GOOGLE" | "FACEBOOK" | "INSTAGRAM";
  badges?: Array<UserBadge>;
  createdAt: Date;
  email: string;
  emailVerified: boolean;
  events?: Array<EventParticipant>;
  groups?: Array<GroupMember>;
  id: string;
  notifications?: Array<Notification>;
  password: string | null;
  phoneNumber: string | null;
  profile?: Profile | null;
  receivedLikes?: Array<Like>;
  receivedMessages?: Array<Message>;
  reports?: Array<Report>;
  roles: string;
  sentLikes?: Array<Like>;
  sentMessages?: Array<Message>;
  socialAccounts?: Array<SocialAccount>;
  stories?: Array<Story>;
  subscription?: Subscription | null;
  trustScore: number;
  updatedAt: Date;
  username: string;
  verificationStatus?: "PENDING" | "VERIFIED" | "REJECTED";
};
