/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Profile as PrismaProfile,
  Interest as PrismaInterest,
  Photo as PrismaPhoto,
  Preference as PrismaPreference,
  User as PrismaUser,
} from "@prisma/client";

export class ProfileServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.ProfileCountArgs, "select">): Promise<number> {
    return this.prisma.profile.count(args);
  }

  async profiles(args: Prisma.ProfileFindManyArgs): Promise<PrismaProfile[]> {
    return this.prisma.profile.findMany(args);
  }
  async profile(
    args: Prisma.ProfileFindUniqueArgs
  ): Promise<PrismaProfile | null> {
    return this.prisma.profile.findUnique(args);
  }
  async createProfile(args: Prisma.ProfileCreateArgs): Promise<PrismaProfile> {
    return this.prisma.profile.create(args);
  }
  async updateProfile(args: Prisma.ProfileUpdateArgs): Promise<PrismaProfile> {
    return this.prisma.profile.update(args);
  }
  async deleteProfile(args: Prisma.ProfileDeleteArgs): Promise<PrismaProfile> {
    return this.prisma.profile.delete(args);
  }

  async findInterests(
    parentId: string,
    args: Prisma.InterestFindManyArgs
  ): Promise<PrismaInterest[]> {
    return this.prisma.profile
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .interests(args);
  }

  async findPhotos(
    parentId: string,
    args: Prisma.PhotoFindManyArgs
  ): Promise<PrismaPhoto[]> {
    return this.prisma.profile
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .photos(args);
  }

  async getPreferences(parentId: string): Promise<PrismaPreference | null> {
    return this.prisma.profile
      .findUnique({
        where: { id: parentId },
      })
      .preferences();
  }

  async getUser(parentId: string): Promise<PrismaUser | null> {
    return this.prisma.profile
      .findUnique({
        where: { id: parentId },
      })
      .user();
  }
}
